### ISSUE TITLE
implement illness and infection as described in the google document

### ISSUE THREAD

**Issue by kwacky1** [kwacky1/text-adventure#54]
### Illness
- [x] Small chance to pick random party member to become ill
- [x] Injury randomly increases
- [x] Messages about them feeling ill
- [x] Morale randomly decreases
- [x] Cannot participate in fights

### Infection
- [x] Similar symptoms to illness 
- [x] Lower chance of curing 
- [x] Messages about them showing aggression 
- [x] Chance of traits randomly changing
- [x] When a party member dies with the infection a zombie fight with be initiated

**Comment by blairdactyl** [comment]
two things not checked?

**Comment by kwacky1** [comment]
These features are actually implemented

https://github.com/kwacky1/text-adventure/blob/0855446a2b748f1e3b93def8f7866fadbaaa02c5/the-wanderers/game.js#L75-L78

https://github.com/kwacky1/text-adventure/blob/0855446a2b748f1e3b93def8f7866fadbaaa02c5/the-wanderers/game.js#L65-L68
